apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deletion-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-deletion
  template:
    metadata:
      labels:
        app: account-deletion
    spec:
      containers:
        - name: account-deletion
          image: raneldahil14/account-deletion-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: account-deletion-secret
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: account-deletion-secret
                  key: DEBUG
            - name: ALLOWED_HOSTS
              valueFrom:
                secretKeyRef:
                  name: account-deletion-secret
                  key: ALLOWED_HOSTS